- name: Setup openHAB
  hosts: localhost
  connection: local
  vars_files:
  - configuration.yml
  - passwords.yml
  roles:
    - common
    - docker
#    - dropbox
    - mosquitto
    - owfs
    - openhab
    - asterisk
