---
# Docker
- name: Docker group
  group:
    name: docker
    gid: 999

- name: Install docker 
  apt: 
    name: docker.io
    update_cache: yes
 
- pip:
    name: docker-py

- name: Start docker daemon
  service:
    name: docker
    state: started

- name: Container present
  docker_container:
    name: dockertest
    image: hello-world

- name: Enable docker
  service:
    name: docker
    enabled: yes 
